"""Tests for Phase D: self-play trained template generators.

Tests cover:
  1. Training data collection — valid triples, pre-1905 only
  2. Template generator training — convergence, output quality
  3. Fallback to hardcoded templates when generator not trained
  4. Generalization to post-1905 symbols
  5. No post-1905 hardcoded formulas in DOMAIN_TEMPLATES
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
import torch

_project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_project_root))

from src.physics.composer import (
    DOMAIN_TEMPLATES,
    DOMAINS,
    ExpressionComposer,
    PerDomainComposer,
    load_self_play_generators,
    load_self_play_composer,
    DomainTemplateGenerator,
    quantities_to_tensor,
    detokenize_expression,
    TEMPLATE_PAD_IDX,
    save_domain_generator,
)
from src.physics.expression_generator import (
    SelfPlayExpressionGenerator,
    PRE_1905_QUANTITY_DIMS,
)


# ═══════════════════════════════════════════════════════════════════════════════
# Test 1: No post-1905 hardcoded templates
# ═══════════════════════════════════════════════════════════════════════════════

class TestNoPost1905Templates:
    """Verify that DOMAIN_TEMPLATES only contains pre-1905 classical domains."""

    def test_quantum_removed(self) -> None:
        assert "quantum" not in DOMAIN_TEMPLATES, (
            "Quantum template should be removed from DOMAIN_TEMPLATES. "
            "It must be generated by a trained model."
        )

    def test_relativistic_removed(self) -> None:
        assert "relativistic" not in DOMAIN_TEMPLATES, (
            "Relativistic template should be removed from DOMAIN_TEMPLATES. "
            "It must be generated by a trained model."
        )

    def test_pre1905_domains_present(self) -> None:
        assert "gravity" in DOMAIN_TEMPLATES
        assert "spring" in DOMAIN_TEMPLATES
        assert "em" in DOMAIN_TEMPLATES
        assert "thermal" in DOMAIN_TEMPLATES
        assert "collision" in DOMAIN_TEMPLATES

    def test_no_post1905_symbols_in_templates(self) -> None:
        """No post-1905 symbols (hbar, c, p, gamma) in any template."""
        post1905 = {"hbar", "c", "p", "gamma"}
        for domain, template in DOMAIN_TEMPLATES.items():
            for sym in post1905:
                assert sym not in template, (
                    f"Post-1905 symbol '{sym}' found in {domain} template: {template}"
                )

    def test_templates_are_valid_expressions(self) -> None:
        """Template strings should be parseable."""
        from src.physics.evaluator import ExpressionEvaluator
        evaluator = ExpressionEvaluator()
        for domain, template in DOMAIN_TEMPLATES.items():
            try:
                evaluator.parse(template)
            except Exception as e:
                pytest.fail(f"Template for '{domain}' fails to parse: {e}")


# ═══════════════════════════════════════════════════════════════════════════════
# Test 2: Self-play training data
# ═══════════════════════════════════════════════════════════════════════════════

class TestSelfPlayData:
    """Verify training data collection produces valid triples."""

    @pytest.fixture
    def generator(self):
        return SelfPlayExpressionGenerator(seed=42, include_hidden_vars=False)

    def test_generator_produces_pre1905_only(self, generator):
        """All generated expressions use only pre-1905 symbols."""
        for level in [1, 2, 3]:
            for _ in range(20):
                result = generator.generate(level)
                qty_symbols = set(result.quantities_dict.keys())
                for q in qty_symbols:
                    assert q in PRE_1905_QUANTITY_DIMS, (
                        f"Post-1905 symbol '{q}' in level {level}: {result.expression_str}"
                    )

    def test_all_expressions_parseable(self, generator):
        """Every generated expression should be parseable."""
        from src.physics.evaluator import ExpressionEvaluator
        evaluator = ExpressionEvaluator()
        for level in [1, 2, 3]:
            for _ in range(10):
                result = generator.generate(level)
                try:
                    evaluator.parse(result.expression_str)
                except Exception as e:
                    pytest.fail(
                        f"Expression '{result.expression_str}' "
                        f"(level {level}) fails to parse: {e}"
                    )

    def test_domain_label_is_valid(self, generator):
        """Domain label should be one of the expected domains."""
        valid_domains = {"gravity", "spring", "thermal", "em",
                         "classical", "mechanics", "gas_law"}
        for _ in range(30):
            result = generator.generate()
            assert result.domain_label in valid_domains, (
                f"Unknown domain: {result.domain_label}"
            )

    def test_generator_at_least_2_quantities(self, generator):
        """Expressions should have 2+ quantities for meaningful templates."""
        for level in [1, 2, 3]:
            for _ in range(10):
                result = generator.generate(level)
                assert len(result.quantities_dict) >= 2, (
                    f"Level {level}: only {len(result.quantities_dict)} quantities "
                    f"in '{result.expression_str}'"
                )


# ═══════════════════════════════════════════════════════════════════════════════
# Test 3: Template generator training
# ═══════════════════════════════════════════════════════════════════════════════

class TestTemplateGeneratorTraining:
    """Verify template generator can train on self-play data."""

    def test_model_initialization(self) -> None:
        model = DomainTemplateGenerator(d_model=48, nhead=2)
        n_params = model.count_parameters()
        assert 20_000 < n_params < 200_000, (
            f"Expected moderate params, got {n_params}"
        )

    def test_gradient_flow(self) -> None:
        """Verify gradients flow through fresh model."""
        model = DomainTemplateGenerator(d_model=48, nhead=2)
        model.train()

        src = quantities_to_tensor(["m", "g", "h", "v"], max_len=8).unsqueeze(0)
        tgt = quantities_to_tensor(["m", "g", "h"], max_len=32).unsqueeze(0)
        tgt_input = tgt[:, :-1]

        logits = model.forward(src, tgt_input)
        loss = logits.sum()
        loss.backward()

        has_grad = any(
            p.grad is not None and p.grad.abs().sum() > 0
            for p in model.parameters()
        )
        assert has_grad, "No gradients flowing"

    def test_save_load_roundtrip(self, tmp_path) -> None:
        """Save and load should preserve weights."""
        model = DomainTemplateGenerator(d_model=48, nhead=2)
        path = tmp_path / "test_gen.pt"
        save_domain_generator(model, str(path))

        loaded = load_self_play_generators(str(tmp_path))
        # Auto-detect won't find it (wrong prefix), so test manually
        from src.physics.composer import load_domain_generator
        loaded2 = load_domain_generator(str(path))
        assert loaded2.count_parameters() == model.count_parameters()

    def test_training_converges_on_synthetic_data(self, tmp_path) -> None:
        """Model should converge on simple synthetic data."""
        import torch.nn as nn
        from torch.utils.data import DataLoader, TensorDataset

        from src.physics.composer import expression_to_tensor

        # Create 100 synthetic examples: {m,g,h} → m*g*h
        src_list: list[torch.Tensor] = []
        tgt_list: list[torch.Tensor] = []
        for _ in range(100):
            src_list.append(quantities_to_tensor(["m", "g", "h"], max_len=8))
            tgt_list.append(expression_to_tensor("m*g*h", max_len=16))

        src_batch = torch.stack(src_list)
        tgt_batch = torch.stack(tgt_list)
        dataset = TensorDataset(src_batch, tgt_batch)
        loader = DataLoader(dataset, batch_size=8, shuffle=True)

        model = DomainTemplateGenerator(d_model=32, nhead=2, max_tgt_len=16)
        model.train()
        optimizer = torch.optim.Adam(model.parameters(), lr=5e-3)
        criterion = nn.CrossEntropyLoss(ignore_index=TEMPLATE_PAD_IDX)

        losses: list[float] = []
        for epoch in range(50):
            epoch_loss = 0.0
            for src, tgt in loader:
                optimizer.zero_grad()
                tgt_input = tgt[:, :-1]
                tgt_output = tgt[:, 1:]
                logits = model.forward(src, tgt_input)
                loss = criterion(
                    logits.reshape(-1, logits.size(-1)),
                    tgt_output.reshape(-1),
                )
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()
            losses.append(epoch_loss / len(loader))

        # Loss should decrease significantly
        assert losses[-1] < losses[0] * 0.3, (
            f"Training did not converge: loss went from {losses[0]:.4f} "
            f"to {losses[-1]:.4f}"
        )

        # Generate should produce the learned template
        model.eval()
        src = quantities_to_tensor(["m", "g", "h"], max_len=8).unsqueeze(0)
        gen_ids = model.generate(src, max_len=16)
        generated = detokenize_expression(gen_ids[0])
        assert "m" in generated and "g" in generated and "h" in generated, (
            f"Generation '{generated}' doesn't contain expected quantities"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# Test 4: Fallback behavior
# ═══════════════════════════════════════════════════════════════════════════════

class TestFallbackBehavior:
    """Verify fallback to DOMAIN_TEMPLATES when generator is untrained."""

    def test_untrained_generator_falls_back(self) -> None:
        """PerDomainComposer with untrained generators should use hardcoded templates."""
        from src.physics.composer import DomainClassifier

        clf = DomainClassifier()
        generators = {
            "gravity": DomainTemplateGenerator(d_model=40, nhead=2),
            "spring": DomainTemplateGenerator(d_model=40, nhead=2),
        }
        composer = PerDomainComposer(clf, generators)

        expr, domains = composer.forward(["m", "g", "h", "v"])
        # Even with untrained generators, forward should not crash
        assert isinstance(expr, str)
        assert isinstance(domains, list)

    def test_fallback_when_no_generator(self) -> None:
        """When domain has no generator, DOMAIN_TEMPLATES should be used."""
        from src.physics.composer import DomainClassifier

        clf = DomainClassifier()
        # Only gravity generator, no spring
        generators = {"gravity": DomainTemplateGenerator(d_model=40, nhead=2)}
        composer = PerDomainComposer(clf, generators)

        expr, domains = composer.forward(["m", "k", "h", "v"])
        assert isinstance(expr, str)
        # Should not crash even without a spring generator


# ═══════════════════════════════════════════════════════════════════════════════
# Test 5: Generalization to post-1905 symbols
# ═══════════════════════════════════════════════════════════════════════════════

class TestGeneralization:
    """Test that template generators generalize to unseen post-1905 symbols."""

    def test_structural_pattern_transfer(self) -> None:
        """A trained generator should produce q1^2 - q2^2 pattern for
        any same-dimension pair, even if symbols are unseen.

        Train on: {m: Mass, g: Accel, h: Length, v: Velocity}
        Test on: {c: Velocity, t: Time, x: Length} → should produce (c*t)^2 - x^2
        """
        import torch.nn as nn
        from torch.utils.data import DataLoader, TensorDataset
        from src.physics.composer import expression_to_tensor, quantities_to_tensor

        # Train on pre-1905 squared differences with multiple patterns
        src_list: list[torch.Tensor] = []
        tgt_list: list[torch.Tensor] = []
        for i in range(300):
            # Train on: {m, v} → m^2 - v^2
            src_list.append(quantities_to_tensor(["m", "v"], max_len=8))
            tgt_list.append(expression_to_tensor("m^2-v^2", max_len=16))
            # Train on: {h, t} → h^2 - t^2
            src_list.append(quantities_to_tensor(["h", "t"], max_len=8))
            tgt_list.append(expression_to_tensor("h^2-t^2", max_len=16))
            # Train on: {E, m} → E^2 - m^2
            src_list.append(quantities_to_tensor(["E", "m"], max_len=8))
            tgt_list.append(expression_to_tensor("E^2-m^2", max_len=16))
            # Train on: {P, V} → P^2 - V^2
            src_list.append(quantities_to_tensor(["P", "V"], max_len=8))
            tgt_list.append(expression_to_tensor("P^2-V^2", max_len=16))

        src_batch = torch.stack(src_list)
        tgt_batch = torch.stack(tgt_list)
        dataset = TensorDataset(src_batch, tgt_batch)
        loader = DataLoader(dataset, batch_size=16, shuffle=True)

        model = DomainTemplateGenerator(d_model=48, nhead=2, max_tgt_len=16)
        model.train()
        optimizer = torch.optim.Adam(model.parameters(), lr=3e-3)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)
        criterion = nn.CrossEntropyLoss(ignore_index=TEMPLATE_PAD_IDX)

        for _ in range(100):
            for src, tgt in loader:
                optimizer.zero_grad()
                tgt_input = tgt[:, :-1]
                tgt_output = tgt[:, 1:]
                # Use causal mask for teacher forcing
                tgt_causal = torch.triu(
                    torch.ones(tgt_input.size(1), tgt_input.size(1))
                    * float("-inf"), diagonal=1,
                )
                logits = model.forward(src, tgt_input, tgt_mask=tgt_causal)
                loss = criterion(
                    logits.reshape(-1, logits.size(-1)),
                    tgt_output.reshape(-1),
                )
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            scheduler.step()

        model.eval()

        # Test on: {c, x} (post-1905 symbols, never seen in training)
        test_src = quantities_to_tensor(["c", "x"], max_len=8).unsqueeze(0)
        gen_ids = model.generate(test_src, max_len=16)
        generated = detokenize_expression(gen_ids[0])

        # The key test: does the model produce a structured expression?
        # We check that the output contains quantities and operators
        has_squared = "^2" in generated
        has_operator = "-" in generated or "+" in generated
        has_vars = any(c.isalpha() for c in generated)
        assert has_vars and (has_squared or has_operator), (
            f"Model should produce structured expression for unseen symbols, "
            f"got: '{generated}'"
        )

    def test_quantity_vocab_includes_post1905(self) -> None:
        """Verify that post-1905 test symbols exist in the template vocabulary."""
        from src.physics.composer import TEMPLATE_TOKEN_TO_ID
        for sym in ["c", "t", "x", "E", "p"]:
            assert sym in TEMPLATE_TOKEN_TO_ID, (
                f"Symbol '{sym}' missing from template vocabulary"
            )


# ═══════════════════════════════════════════════════════════════════════════════
# Test 6: Integration tests for Phase D
# ═══════════════════════════════════════════════════════════════════════════════

class TestPhaseDIntegration:
    """End-to-end integration tests for Phase D."""

    def test_load_self_play_generators_auto_detect(self, tmp_path) -> None:
        """load_self_play_generators should auto-detect checkpoints."""
        # Create test checkpoints
        for domain in ["gravity", "spring"]:
            model = DomainTemplateGenerator(d_model=40, nhead=2)
            path = tmp_path / f"self_play_{domain}_template.pt"
            save_domain_generator(model, str(path))

        generators = load_self_play_generators(str(tmp_path))
        assert "gravity" in generators
        assert "spring" in generators
        assert all(isinstance(g, DomainTemplateGenerator) for g in generators.values())

    def test_load_self_play_composer(self, tmp_path) -> None:
        """load_self_play_composer should return a working composer."""
        # Create minimal checkpoints
        for domain in ["gravity", "spring", "thermal"]:
            model = DomainTemplateGenerator(d_model=40, nhead=2)
            path = tmp_path / f"self_play_{domain}_template.pt"
            save_domain_generator(model, str(path))

        composer = load_self_play_composer(str(tmp_path))
        assert isinstance(composer, PerDomainComposer)

        # Should work on gravity inputs
        expr, domains = composer.forward(["m", "g", "h", "v"])
        assert isinstance(expr, str)
        assert "gravity" in domains

    def test_pipeline_with_trained_generators(self, tmp_path) -> None:
        """Pipeline should prefer trained generator output over hardcoded templates."""
        import torch.nn as nn
        from torch.utils.data import DataLoader, TensorDataset
        from src.physics.composer import expression_to_tensor

        # Train a gravity generator to output a specific template
        src_list = []
        tgt_list = []
        for _ in range(100):
            src_list.append(quantities_to_tensor(["m", "g", "h", "v"], max_len=8))
            tgt_list.append(expression_to_tensor("m*g*h + 0.5*m*v^2", max_len=32))

        src_batch = torch.stack(src_list)
        tgt_batch = torch.stack(tgt_list)
        dataset = TensorDataset(src_batch, tgt_batch)
        loader = DataLoader(dataset, batch_size=8, shuffle=True)

        model = DomainTemplateGenerator(d_model=32, nhead=2)
        model.train()
        optimizer = torch.optim.Adam(model.parameters(), lr=5e-3)
        criterion = nn.CrossEntropyLoss(ignore_index=TEMPLATE_PAD_IDX)

        for _ in range(50):
            for src, tgt in loader:
                optimizer.zero_grad()
                tgt_input = tgt[:, :-1]
                tgt_output = tgt[:, 1:]
                logits = model.forward(src, tgt_input)
                loss = criterion(
                    logits.reshape(-1, logits.size(-1)),
                    tgt_output.reshape(-1),
                )
                loss.backward()
                optimizer.step()

        model.eval()

        # Save trained generator
        ckpt_dir = Path(tmp_path)
        save_domain_generator(model, str(ckpt_dir / "self_play_gravity_template.pt"))

        # Load composer
        composer = load_self_play_composer(str(ckpt_dir))
        expr, domains = composer.forward(["m", "g", "h", "v"])

        # The generated expression should contain the expected quantities
        assert "m" in expr, f"Expression '{expr}' missing 'm'"
        assert "g" in expr, f"Expression '{expr}' missing 'g'"
