#!/usr/bin/env python3
"""Pure Math Self-Play Pipeline.

Train template generators on 100K+ mathematical identities (algebraic,
trigonometric, exponential, structural invariants), then test TRANSFER
to physics: does math training help discover MORE physics invariants
than physics-only training?

Physics baseline era gate: 6/15 verified.
Math target: >6/15 — the system should learn GENERAL structural patterns
(a^2-b^2, sin^2+cos^2, a*b=b*a) that transfer across domains.

ARCHITECTURE:
  1. Generate 100K+ math identities with noisy observations
  2. Train ONE general math DomainTemplateGenerator
  3. Clone it to all physics domain slots (self_play_{domain}_template.pt)
  4. Run verify_8_claims.py and spacetime_era_gate.py
  5. Save checkpoints and results

CPU only. Max 6 threads for training. Eval uses 4 threads.
Never 2 parallel training processes.

Usage:
    python scripts/training/math_self_play_pipeline.py
    python scripts/training/math_self_play_pipeline.py --n-identities 50000
    python scripts/training/math_self_play_pipeline.py --epochs 30
    python scripts/training/math_self_play_pipeline.py --skip-train  # reuse existing checkpoint
"""

from __future__ import annotations

import argparse
import json
import math as _math
import os
import random
import sys
import time
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# ── Math-specific symbol pool ──────────────────────────────────────────────
# Maps math identity variables to vocab-compatible symbols.
# All symbols must be in QUANTITY_VOCAB / TEMPLATE_TOKENS.
# We use a fixed pool of 52 symbols (enough for complex identities like
# det product with 8 variables) and cycle through them.
_MATH_SYMBOL_POOL = [
    # Single letters (a-z all in vocab)
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
    "u", "v", "w", "x", "y", "z",
    # Multi-letter fallbacks
    "a0", "a1", "b0", "b1", "c0", "c1", "d0", "d1",
    "e0", "e1", "f0", "f1", "g0", "g1", "h0", "h1",
    "v1", "v2", "x1", "x2", "m1", "m2", "q1", "q2",
    "L", "B", "W", "Q",
]


def _remap_symbols_for_invariant(inv) -> dict[str, str]:
    """Create a mapping from original math variable names to vocab symbols."""
    # The MathInvariant has a list of variable names generated by _next_symbol().
    # We remap them to our pool so they're all in QUANTITY_VOCAB.
    mapping: dict[str, str] = {}
    pool_idx = 0
    for orig_var in inv.variables:
        # First check if it's already a valid token
        from src.physics.composer import TEMPLATE_TOKEN_TO_ID
        if orig_var in TEMPLATE_TOKEN_TO_ID:
            mapping[orig_var] = orig_var
        else:
            # Use next pool symbol
            mapping[orig_var] = _MATH_SYMBOL_POOL[pool_idx % len(_MATH_SYMBOL_POOL)]
            pool_idx += 1
    return mapping


def _remap_expression(expr: str, mapping: dict[str, str]) -> str:
    """Remap variable names in an expression string."""
    result = expr
    # Sort by length (longest first) to avoid partial matches
    for orig, new in sorted(mapping.items(), key=lambda x: -len(x[0])):
        result = result.replace(orig, new)
    return result


# ── Math identity -> training example ──────────────────────────────────────

def identity_to_example(inv, noise_frac: float, rng: random.Random,
                        n_observations: int = 10) -> dict[str, Any] | None:
    """Convert a MathInvariant to a template training example.

    Each example has:
      - quantities: list of variable symbols (input to template generator)
      - domain: identity type (algebraic, trigonometric, etc.)
      - expression: the invariant expression (training target)
      - complexity: 1-5
      - noisy_observations: list of noisy value samples (for verification)

    Returns None if the identity can't be mapped (symbol not in vocab).
    """
    from src.physics.composer import TEMPLATE_TOKEN_TO_ID

    # Remap variables to vocab-compatible symbols
    mapping = _remap_symbols_for_invariant(inv)

    # Check all mapped symbols are valid
    for orig, new in mapping.items():
        if new not in TEMPLATE_TOKEN_TO_ID:
            # This shouldn't happen with our pool, but guard against it
            return None

    # Remap expression
    expr_remapped = _remap_expression(inv.expression, mapping)

    # Check expression is tokenizable
    try:
        from src.physics.composer import tokenize_expression, TEMPLATE_UNK_IDX
        tokens = tokenize_expression(expr_remapped)
        # Allow some UNK tokens (single-char variables that happen to not match)
        # but reject if too many unknowns
        unk_ratio = sum(1 for t in tokens if t == TEMPLATE_UNK_IDX) / max(len(tokens), 1)
        if unk_ratio > 0.3:
            return None
    except Exception:
        return None

    # Remap variables list
    var_list = sorted(set(mapping.values()))

    # Generate noisy observations
    try:
        raw_values = inv.generate_values(n_observations, rng)
    except Exception:
        return None

    noisy_observations = []
    for raw in raw_values:
        obs = {}
        for orig_var, orig_val in raw.items():
            new_var = mapping.get(orig_var, orig_var)
            # Add Gaussian noise to simulate measurement error
            obs[new_var] = orig_val * rng.gauss(1.0, noise_frac)
        noisy_observations.append(obs)

    return {
        "quantities": var_list,
        "domain": inv.identity_type,
        "expression": expr_remapped,
        "complexity": inv.complexity,
        "description": inv.description,
        "noisy_observations": noisy_observations,
    }


# ── Data generation ────────────────────────────────────────────────────────

def generate_math_training_data(
    n_identities: int = 100_000,
    noise_frac: float = 0.02,
    seed: int = 42,
    output_path: str | Path = "data/math_self_play_training.jsonl",
) -> tuple[list[dict], int]:
    """Generate math identity training data.

    Returns:
        (list of training examples, number of identities attempted)
    """
    from src.math import MathInvariantGenerator, reset_symbol_pool

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rng = random.Random(seed)
    gen = MathInvariantGenerator(seed=seed)

    # Track stats
    type_counts: dict[str, int] = defaultdict(int)
    examples: list[dict] = []
    attempts = 0
    max_attempts = n_identities * 3  # safety limit

    print(f"Generating up to {n_identities} math identities...")
    print(f"Noise fraction: {noise_frac*100:.0f}%")
    print(f"Available invariant types: {gen.available_types}")

    # Balance across all types
    all_types = gen.available_types

    while len(examples) < n_identities and attempts < max_attempts:
        attempts += 1

        # Cycle through all types for balanced coverage
        inv_type = all_types[attempts % len(all_types)]
        try:
            inv = gen.generate(type_filter=inv_type)
        except Exception:
            continue

        example = identity_to_example(inv, noise_frac, rng)
        if example is None:
            continue

        examples.append(example)
        type_counts[inv.identity_type] += 1

        if len(examples) % 5000 == 0:
            print(f"  Generated {len(examples):,} / {n_identities:,} "
                  f"(attempts: {attempts:,})")

    # Write JSONL
    with open(output_path, "w") as f:
        for ex in examples:
            json.dump(ex, f)
            f.write("\n")

    print(f"\nGenerated {len(examples):,} training examples "
          f"(from {attempts:,} attempts)")
    print(f"Type distribution:")
    for t, c in sorted(type_counts.items()):
        print(f"  {t:30s}: {c:6,}")

    return examples, attempts


# ── Math template dataset ──────────────────────────────────────────────────

class MathTemplateDataset(torch.utils.data.Dataset):
    """Dataset for training template generator from math identities.

    Input: variable symbols → Output: expression string.
    Domain-agnostic: we train ONE model on all identity types.
    """

    def __init__(
        self,
        examples: list[dict],
        src_max_len: int = 10,
        tgt_max_len: int = 48,
    ):
        from src.physics.composer import (
            quantities_to_tensor, expression_to_tensor,
            TEMPLATE_TOKEN_TO_ID, TEMPLATE_UNK_IDX,
        )

        self.samples: list[tuple[torch.Tensor, torch.Tensor]] = []

        for ex in examples:
            qty_symbols = ex.get("quantities", [])
            # Filter to only valid vocab symbols
            qty_symbols = [q for q in qty_symbols if q in TEMPLATE_TOKEN_TO_ID]
            if len(qty_symbols) < 1:
                continue

            expr = ex.get("expression", "")
            if not expr or not expr.strip():
                continue

            # Sort for consistency
            qty_sorted = sorted(qty_symbols)
            src = quantities_to_tensor(qty_sorted, max_len=src_max_len)

            # Target expression
            tgt = expression_to_tensor(expr, max_len=tgt_max_len)

            self.samples.append((src, tgt))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        return self.samples[idx]


# ── Training ───────────────────────────────────────────────────────────────

def train_math_template_generator(
    examples: list[dict],
    checkpoint_path: str | Path,
    epochs: int = 50,
    lr: float = 1e-3,
    batch_size: int = 64,
    device: torch.device = torch.device("cpu"),
    d_model: int = 64,
    nhead: int = 4,
) -> tuple[nn.Module, dict]:
    """Train one general math template generator.

    Uses a slightly larger model (64-dim, 4-head) than domain-specific ones
    (48-dim, 2-head) because it must cover all identity types.
    """
    from src.physics.composer import (
        DomainTemplateGenerator,
        TEMPLATE_PAD_IDX, TEMPLATE_VOCAB_SIZE,
    )

    print(f"\n{'=' * 60}")
    print(f"Training Math Template Generator")
    print(f"{'=' * 60}")

    dataset = MathTemplateDataset(examples, src_max_len=10, tgt_max_len=48)
    n_samples = len(dataset)
    print(f"  Training examples: {n_samples:,}")

    if n_samples == 0:
        raise ValueError("No valid training examples")

    dataloader = DataLoader(
        dataset,
        batch_size=min(batch_size, n_samples),
        shuffle=True,
        drop_last=True,
    )

    model = DomainTemplateGenerator(
        d_model=d_model,
        nhead=nhead,
        max_src_len=10,
        max_tgt_len=48,
        vocab_size=TEMPLATE_VOCAB_SIZE,
    )
    n_params = model.count_parameters()
    print(f"  Parameters: {n_params:,}")
    print(f"  Vocab size: {TEMPLATE_VOCAB_SIZE}")
    print(f"  d_model={d_model}, nhead={nhead}")

    criterion = nn.CrossEntropyLoss(ignore_index=TEMPLATE_PAD_IDX)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    stats: dict[str, list[float]] = {
        "train_loss": [], "train_acc": [], "epoch_time": [],
    }

    model.train()
    model.to(device)

    best_loss = float("inf")

    for epoch in range(1, epochs + 1):
        t_start = time.time()
        epoch_loss = 0.0
        epoch_correct = 0
        epoch_total = 0
        n_batches = 0

        for src, tgt in dataloader:
            src = src.to(device)
            tgt = tgt.to(device)

            optimizer.zero_grad()

            # Teacher forcing
            tgt_input = tgt[:, :-1]
            tgt_output = tgt[:, 1:]

            logits = model(src, tgt_input)
            # logits: [batch, tgt_len-1, vocab_size]
            loss = criterion(
                logits.reshape(-1, logits.size(-1)),
                tgt_output.reshape(-1),
            )
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

            # Accuracy (teacher-forced)
            preds = logits.argmax(dim=-1)
            mask = tgt_output != TEMPLATE_PAD_IDX
            epoch_correct += (preds == tgt_output)[mask].sum().item()
            epoch_total += mask.sum().item()

        scheduler.step()

        avg_loss = epoch_loss / n_batches
        avg_acc = epoch_correct / max(epoch_total, 1)
        epoch_time = time.time() - t_start

        stats["train_loss"].append(avg_loss)
        stats["train_acc"].append(avg_acc)
        stats["epoch_time"].append(epoch_time)

        if avg_loss < best_loss:
            best_loss = avg_loss
            # Save best checkpoint
            from src.physics.composer import save_domain_generator
            save_domain_generator(model, str(checkpoint_path))
            saved = True
        else:
            saved = False

        marker = " *" if saved else ""
        print(f"  Epoch {epoch:3d}/{epochs} | loss={avg_loss:.4f} "
              f"acc={avg_acc:.3f} time={epoch_time:.1f}s{marker}")

    # Load best
    from src.physics.composer import load_domain_generator
    model = load_domain_generator(str(checkpoint_path))
    model.eval()

    print(f"\n  Final checkpoint → {checkpoint_path}")
    print(f"  Best loss: {best_loss:.4f}")
    return model, stats


# ── Clone to domain slots ─────────────────────────────────────────────────

def clone_to_domain_slots(
    math_ckpt_path: str | Path,
    domains: list[str],
    checkpoint_dir: str | Path = "checkpoints",
) -> list[str]:
    """Clone math template generator to physics domain slots.

    Saves copies as self_play_{domain}_template.pt for each domain.
    """
    import shutil

    checkpoint_dir = Path(checkpoint_dir)
    saved: list[str] = []

    math_ckpt = Path(math_ckpt_path)
    if not math_ckpt.exists():
        print(f"ERROR: Math checkpoint not found at {math_ckpt}")
        return saved

    for domain in domains:
        dest = checkpoint_dir / f"self_play_{domain}_template.pt"
        # Backup existing
        if dest.exists():
            backup = checkpoint_dir / f"self_play_{domain}_template_backup.pt"
            if not backup.exists():
                shutil.copy(dest, backup)
                print(f"  Backed up existing → {backup}")
        shutil.copy(math_ckpt, dest)
        saved.append(str(dest))
        print(f"  Cloned → {dest}")

    return saved


# ── Evaluation helpers ─────────────────────────────────────────────────────

def run_verify_8_claims(noise_frac: float, seed: int) -> dict:
    """Run verify_8_claims.py and parse results."""
    import subprocess

    script = PROJECT_ROOT / "scripts" / "verify_8_claims.py"
    cmd = [
        sys.executable, str(script),
        "--honest-data",
        "--noise", str(noise_frac),
        "--seed", str(seed),
    ]

    print(f"\n{'=' * 60}")
    print("Running verify_8_claims.py (math-trained generators)")
    print(f"  Command: {' '.join(cmd)}")
    print(f"{'=' * 60}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        env=env,
        timeout=600,  # 10 min
    )

    stdout = result.stdout
    stderr = result.stderr

    print(stdout[-2000:] if len(stdout) > 2000 else stdout)
    if stderr:
        print(f"STDERR: {stderr[-500:]}")

    # Parse results
    passed = stdout.count("PASS")
    failed = stdout.count("FAIL")
    total = passed + failed

    return {
        "passed": passed,
        "failed": failed,
        "total": total,
        "stdout_tail": stdout[-3000:] if len(stdout) > 3000 else stdout,
        "stderr_tail": stderr[-500:] if stderr else "",
        "returncode": result.returncode,
    }


def run_spacetime_era_gate(era_cutoff: int = 1905) -> dict:
    """Run spacetime_era_gate.py and parse results."""
    import subprocess

    script = PROJECT_ROOT / "scripts" / "spacetime_era_gate.py"
    cmd = [
        sys.executable, str(script),
        "--era-cutoff", str(era_cutoff),
    ]

    print(f"\n{'=' * 60}")
    print(f"Running spacetime_era_gate.py (cutoff={era_cutoff}, math-trained)")
    print(f"  Command: {' '.join(cmd)}")
    print(f"{'=' * 60}")

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
        env=env,
        timeout=900,  # 15 min
    )

    stdout = result.stdout
    stderr = result.stderr

    print(stdout[-2000:] if len(stdout) > 2000 else stdout)
    if stderr:
        print(f"STDERR: {stderr[-500:]}")

    # Parse — count "VERIFIED" lines
    verified = stdout.count("spacetime_verified") + stdout.count("VERIFIED")
    discovered = stdout.count("discovered=True") + stdout.count("DISCOVERED")

    return {
        "verified": verified,
        "discovered": discovered,
        "stdout_tail": stdout[-3000:] if len(stdout) > 3000 else stdout,
        "stderr_tail": stderr[-500:] if stderr else "",
        "returncode": result.returncode,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Main Pipeline
# ═══════════════════════════════════════════════════════════════════════════

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Pure Math Self-Play Pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/training/math_self_play_pipeline.py
  python scripts/training/math_self_play_pipeline.py --n-identities 50000 --epochs 30
  python scripts/training/math_self_play_pipeline.py --skip-train  # reuse existing ckpt
  python scripts/training/math_self_play_pipeline.py --skip-eval   # train only
""",
    )
    parser.add_argument("--n-identities", type=int, default=100_000,
                        help="Number of math identities to generate")
    parser.add_argument("--epochs", type=int, default=50,
                        help="Training epochs")
    parser.add_argument("--noise", type=float, default=0.02,
                        help="Measurement noise fraction")
    parser.add_argument("--lr", type=float, default=1e-3,
                        help="Learning rate")
    parser.add_argument("--batch-size", type=int, default=64,
                        help="Training batch size")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed")
    parser.add_argument("--skip-train", action="store_true",
                        help="Skip training (use existing checkpoint)")
    parser.add_argument("--skip-eval", action="store_true",
                        help="Skip evaluation")
    parser.add_argument("--era-cutoff", type=int, default=1905,
                        help="Era cutoff for spacetime gate evaluation")

    args = parser.parse_args()

    # Set thread counts
    torch.set_num_threads(6)
    device = torch.device("cpu")

    # Paths
    data_path = PROJECT_ROOT / "data" / "math_self_play_training.jsonl"
    checkpoint_dir = PROJECT_ROOT / "checkpoints" / "math_self_play"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    math_ckpt = checkpoint_dir / "math_template.pt"
    results_path = PROJECT_ROOT / "data" / "math_self_play_results.json"

    results: dict[str, Any] = {
        "config": vars(args),
        "timestamp": time.time(),
        "phases": {},
    }

    # ═══════════════════════════════════════════════════════════════════════
    # Phase 1: Generate math training data
    # ═══════════════════════════════════════════════════════════════════════
    t0 = time.time()
    if not args.skip_train or not data_path.exists():
        print("=" * 60)
        print("PHASE 1: Generate math identity training data")
        print("=" * 60)

        examples, attempts = generate_math_training_data(
            n_identities=args.n_identities,
            noise_frac=args.noise,
            seed=args.seed,
            output_path=data_path,
        )

        results["phases"]["data_generation"] = {
            "n_examples": len(examples),
            "n_attempts": attempts,
            "valid_ratio": len(examples) / max(attempts, 1),
            "time_s": time.time() - t0,
        }
        print(f"  Valid ratio: {len(examples)/max(attempts,1):.1%}")
    else:
        print(f"Phase 1: Using existing data at {data_path}")
        examples = []
        with open(data_path) as f:
            for line in f:
                if line.strip():
                    examples.append(json.loads(line))
        print(f"  Loaded {len(examples):,} examples")

    # ═══════════════════════════════════════════════════════════════════════
    # Phase 2: Train math template generator
    # ═══════════════════════════════════════════════════════════════════════
    t0 = time.time()
    if not args.skip_train:
        print("\n" + "=" * 60)
        print("PHASE 2: Train math template generator")
        print("=" * 60)

        model, train_stats = train_math_template_generator(
            examples=examples,
            checkpoint_path=math_ckpt,
            epochs=args.epochs,
            lr=args.lr,
            batch_size=args.batch_size,
            device=device,
            d_model=64,
            nhead=4,
        )

        results["phases"]["training"] = {
            "epochs": len(train_stats["train_loss"]),
            "final_loss": train_stats["train_loss"][-1],
            "final_acc": train_stats["train_acc"][-1],
            "best_loss": min(train_stats["train_loss"]),
            "total_time_s": time.time() - t0,
        }
    else:
        print(f"\nPhase 2: Skipping training, using {math_ckpt}")

    # ═══════════════════════════════════════════════════════════════════════
    # Phase 3: Clone to physics domain slots
    # ═══════════════════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("PHASE 3: Clone math generator to physics domain slots")
    print("=" * 60)

    physics_domains = ["gravity", "spring", "em", "thermal", "collision"]
    saved = clone_to_domain_slots(math_ckpt, physics_domains, PROJECT_ROOT / "checkpoints")
    results["phases"]["clone"] = {"domains": physics_domains, "paths": saved}

    # ═══════════════════════════════════════════════════════════════════════
    # Phase 4: Evaluate on physics (verify_8_claims)
    # ═══════════════════════════════════════════════════════════════════════
    if not args.skip_eval:
        print("\n" + "=" * 60)
        print("PHASE 4: Evaluate on physics (transfer test)")
        print("=" * 60)

        # verify_8_claims
        verify_result = run_verify_8_claims(args.noise, args.seed)
        results["phases"]["verify_8_claims"] = verify_result
        print(f"\n  verify_8_claims: {verify_result['passed']}/{verify_result['total']} passed")

        # spacetime_era_gate
        era_result = run_spacetime_era_gate(args.era_cutoff)
        results["phases"]["spacetime_era_gate"] = era_result
        print(f"\n  spacetime_era_gate: {era_result['verified']} verified")

    # ═══════════════════════════════════════════════════════════════════════
    # Phase 5: Summary
    # ═══════════════════════════════════════════════════════════════════════
    results["total_time_s"] = time.time() - results["timestamp"]

    # Save results
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nResults saved → {results_path}")

    # Summary
    print(f"\n{'=' * 60}")
    print("MATH SELF-PLAY PIPELINE COMPLETE")
    print(f"{'=' * 60}")
    if "data_generation" in results["phases"]:
        print(f"  Math identities: {results['phases']['data_generation']['n_examples']:,}")
    if "training" in results["phases"]:
        print(f"  Best loss: {results['phases']['training']['best_loss']:.4f}")
        print(f"  Final acc: {results['phases']['training']['final_acc']:.3f}")
    if "verify_8_claims" in results["phases"]:
        v = results["phases"]["verify_8_claims"]
        print(f"  verify_8_claims: {v['passed']}/{v['total']}")
    if "spacetime_era_gate" in results["phases"]:
        s = results["phases"]["spacetime_era_gate"]
        print(f"  spacetime_era_gate: {s['verified']} verified, {s['discovered']} discovered")
    print(f"  Total time: {results['total_time_s']:.0f}s")

    # Comparison
    print(f"\n  Physics self-play baseline: 6/15 era gate")
    if "spacetime_era_gate" in results["phases"]:
        math_verified = results["phases"]["spacetime_era_gate"]["verified"]
        print(f"  Math self-play era gate:   {math_verified}/15")
        if math_verified > 6:
            print(f"  >>> IMPROVEMENT: +{math_verified - 6}")
        elif math_verified == 6:
            print(f"  === MATCH: same as physics baseline")
        else:
            print(f"  --- DEGRADATION: {math_verified - 6}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
