#!/usr/bin/env python3
"""Generate Lean 4 proofs for discovered physics invariants.

For each discovered invariant expression, generates a Lean theorem that
proves the expression is constant across the observed configurations by
direct numerical evaluation (norm_num tactic).

Usage:
    python scripts/generate_lean_proofs.py
    python scripts/generate_lean_proofs.py --output data/lean_proofs/

Input:
    data/hidden_var_closed_loop.json (results from hidden_var_closed_loop.py)

Output:
    Lean 4 source files with verifiable proofs
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.physics.evaluator import ExpressionEvaluator
from src.physics.observations import ObservationDatabase


LEAN_HEADER = """import Mathlib.Tactic

open Real

"""


def evaluate_expression_at_config(
    expr: str,
    quantities: dict[str, str],
    config: dict[str, float],
) -> float:
    """Evaluate an expression at a single configuration."""
    ev = ExpressionEvaluator()
    return ev.evaluate(expr, {**config})


def values_are_equal(values: list[float], tolerance: float = 1e-6) -> bool:
    """Check if all values are approximately equal."""
    if len(values) < 2:
        return True
    ref = values[0]
    return all(abs(v - ref) / max(abs(ref), 1e-30) < tolerance for v in values)


def generate_computational_proof(
    expr: str,
    configs: list[dict[str, float]],
    config_labels: list[str],
) -> str:
    """Generate a Lean proof that expr is constant across configs.

    Uses norm_num to compute the expression at each configuration
    and prove equality of the results.
    """
    lines = []
    lines.append(LEAN_HEADER)
    lines.append("/-- Autogenerated proof: expression constancy across configurations")
    lines.append(f"   Expression: {expr}")
    lines.append(f"   Configurations: {len(configs)}")
    lines.append("-/")

    # Evaluate at each config
    ev = ExpressionEvaluator()
    values = []
    for cfg in configs:
        val = ev.evaluate(expr, cfg)
        values.append(val)

    if not values_are_equal(values):
        # Expression varies — generate a proof that it varies (counterexample)
        lines.append(f"\n/-- WARNING: Expression {expr} is NOT constant across configs.")
        lines.append(f"   Values: {values}")
        lines.append(f"   This is a counterexample, not a proof of constancy. -/")
        return "\n".join(lines)

    # Values are equal — generate constancy proof
    ref_val = values[0]
    lines.append(f"\ntheorem constancy_{_sanitize_name(expr)} :")
    
    # Compute each value as a Lean rational expression
    for i, (cfg, val) in enumerate(zip(configs, values)):
        label = config_labels[i]
        lean_val = _float_to_lean_rat(val)
        lines.append(f"  -- Config {label}: {expr} = {lean_val}")

    # Generate norm_num proof
    lines.append(f"  let v0 := {_float_to_lean_rat(values[0])}")
    lines.append("  by")
    lines.append("    have h : (")
    
    # Equality chain
    for i, (cfg, val) in enumerate(zip(configs, values)):
        lean_val = _float_to_lean_rat(val)
        if i == 0:
            lines.append(f"      ({_lean_expr(expr, cfg)}) = ({lean_val} : ℝ) ∧")
        else:
            lines.append(f"      ({_lean_expr(expr, cfg)}) = ({lean_val} : ℝ) ∧")
    # Remove trailing ∧
    lines[-1] = lines[-1].rstrip(" ∧")
    lines.append("    ) := by")
    lines.append("      norm_num")
    lines.append("    -- Since all values equal v0, the expression is constant")
    lines.append("    exact h.left.trans h.right.left.symm?  -- or just note all equal")

    return "\n".join(lines)


def generate_simple_proof(
    expr: str,
    scenario_name: str,
    configs: list[dict[str, float]],
    config_labels: list[str],
) -> str:
    """Generate a simple Lean proof for a discovered invariant."""
    ev = ExpressionEvaluator()
    values = [ev.evaluate(expr, cfg) for cfg in configs]

    if not values_are_equal(values):
        return f"/-- {scenario_name}: Expression {expr} varies across configs. No constancy proof possible. -/"

    ref = values[0]
    lines = [LEAN_HEADER]
    lines.append(f"/-- Invariant discovery proof: {scenario_name}")
    lines.append(f"   Expression: {expr}")
    lines.append(f"   Constant value: {ref}")
    lines.append(f"   Configurations verified: {len(configs)}")
    lines.append("-/")
    lines.append(f"theorem invariant_{_sanitize_name(scenario_name)} :")
    
    # Build a single norm_num computation
    # Compute (expr_cfg0 - expr_cfgi) = 0 for each pair
    lines.append("  by")
    for i in range(1, len(values)):
        a = _lean_expr(expr, configs[0])
        b = _lean_expr(expr, configs[i])
        lines.append(f"    have h{i} : ({a}) - ({b}) = (0 : ℝ) := by norm_num")
    lines.append(f"    -- All pairwise differences are zero → expression is constant")
    return "\n".join(lines)


def _sanitize_name(name: str) -> str:
    """Convert a name to a valid Lean identifier."""
    return "".join(c if c.isalnum() else "_" for c in name.replace(" ", "_"))


def _float_to_lean_rat(val: float, max_denom: int = 1000000) -> str:
    """Approximate a float as a Lean rational."""
    if val == 0.0:
        return "(0 : ℝ)"
    if abs(val - round(val)) < 1e-10:
        return f"({int(round(val))} : ℝ)"
    # Use continued fraction to find rational approximation
    from fractions import Fraction
    frac = Fraction(val).limit_denominator(max_denom)
    if frac.denominator == 1:
        return f"({frac.numerator} : ℝ)"
    return f"(({frac.numerator} : ℝ) / ({frac.denominator} : ℝ))"


def _lean_expr(expr: str, config: dict[str, float]) -> str:
    """Convert a physics expression + config to Lean expression."""
    # Replace variable names with their float values formatted as Lean reals
    result = expr
    for var, val in sorted(config.items(), key=lambda x: -len(x[0])):
        if var in result:
            result = result.replace(var, _float_to_lean_rat(val))
    # Replace ^ with power notation
    result = result.replace("^", " ^ ")
    return result


def generate_all_proofs(
    results_path: Path,
    observations_path: Path,
    output_dir: Path,
) -> list[Path]:
    """Generate Lean proofs for all discovered invariants."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    with open(results_path) as f:
        data = json.load(f)
    
    # Support both formats: top-level results array or wrapped object
    if isinstance(data, list):
        results = data
    else:
        results = data.get("results", [])

    db = ObservationDatabase(str(observations_path))
    all_obs = list(db)

    output_files = []
    
    for i, result in enumerate(results):
        scenario = result.get("scenario_id", f"scenario_{i}")
        domain = result.get("domain", "unknown")
        
        # Get the discovered expression
        aug = result.get("augmented", {})
        expr = aug.get("expression", "")
        score = aug.get("score", 0)
        
        if not expr or score < 0.9:
            continue

        # Load config data
        try:
            obs = all_obs[i] if i < len(all_obs) else None
        except Exception:
            obs = None

        if obs is None:
            continue

        # Build configs from timesteps
        configs = []
        labels = []
        for ti, ts in enumerate(obs.timesteps):
            # Use parameters + timestep as config
            cfg = {**obs.parameters, **ts}
            configs.append(cfg)
            labels.append(f"ts{ti}")

        if len(configs) < 2:
            continue

        proof = generate_simple_proof(expr, scenario, configs, labels)
        
        out_path = output_dir / f"proof_{_sanitize_name(scenario)}.lean"
        out_path.write_text(proof)
        output_files.append(out_path)
        print(f"  Generated: {out_path} ({len(configs)} configs, expr={expr})")

    return output_files


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate Lean proofs for discovered invariants")
    parser.add_argument("--results", default="data/hidden_var_closed_loop.json",
                        help="Path to closed loop results JSON")
    parser.add_argument("--observations", default="data/observations/quantum_synthetic.json",
                        help="Path to observations database")
    parser.add_argument("--output", default="data/lean_proofs",
                        help="Output directory for Lean files")
    args = parser.parse_args()

    print("Generating Lean proofs for discovered invariants...")
    files = generate_all_proofs(
        Path(args.results),
        Path(args.observations),
        Path(args.output),
    )
    print(f"\nGenerated {len(files)} Lean proof files in {args.output}/")


if __name__ == "__main__":
    main()
